lecture3/bday/urls.py
from django.urls import path
from . import views
app_name='bday'
urlpatterns=[
    path("",views.isit,name="birthday")
]

lecture3/hi/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("",views.index,name="index"),
    path("parteek",views.parteek,name="myname"),
    path("<int:num1>",views.square,name="sq"),
    path("fcb",views.fcb,name="club"),
    
]

lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hi/', include("hi.urls")),
    path('bday/', include("bday.urls")),
    path('tasks/',include("tasks.urls"))

]

lecture3/tasks/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path("",views.li,name="greek")
]

lecture3/bday/models.py
from django.db import models

# Create your models here.

lecture3/hi/models.py
from django.db import models

# Create your models here.

lecture3/tasks/models.py
from django.db import models

# Create your models here.

lecture3/bday/views.py
from django.shortcuts import render
from django.http import HttpResponse
import datetime
# Create your views here.

def isit(request):
    now=datetime.datetime.now()
    return render(request,"hello/index.html",{
        "bday":now.month==10 and now.day==12,"day":now.day,"month":now.month,"yr":now.year
    })

lecture3/hi/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    return HttpResponse("Hello")

def parteek(request):
    return HttpResponse(", Parteek")

def square(request, num1):
    return render(request, "hello/sq.html", {
        "num": num1,"res": num1*num1
    }) 

def fcb(request):
    return render(request, "hello/fcb.html")

lecture3/tasks/views.py
from django.shortcuts import render
from django import forms
# Create your views here.


class newalph(forms.Form):
    task=forms.CharField(label="New Alphabet")
    prt=forms.IntegerField(label="Priority",max_value=10)
def li(request):
    if "tasks" not in request.session:
        request.session["tasks"]=[]
    if request.method=="POST":
        form=newalph(request.POST)
        if form.is_valid():
            task= form.cleaned_data["task"]
            request.session["tasks"] += [task]
    return render(request,"tasks/index.html",{
        "letters":request.session["tasks"],"form":newalph(),
    })

lecture3/bday/templates/hello/index.html
<!DOCTYPE html>
<head>
    <title>Birthday</title>
</head>
<body>
    <h1>The date is {{day}}/{{month}}/{{year}}</h1>
   {% if bday %}
    <h2>It is my Birthday</h2>
    {% else %}
    <h2>It is not my Birthday</h2>
    {% endif %}
</body>

lecture3/hi/templates/hello/fcb.html
{% load static %}
<!DOCTYPE html>
  <html>
      <link rel="stylesheet" href="{% static 'styles/fcbsty.css' %}">
      <link rel="stylesheet" href="{% static 'styles/bootstrap.css' %}">
      <head>
          <h1>FC Barcelona</h1>
      </head>
      <body>
          <div id="img">
          <img src="{% static 'styles/fcb.png' %}" height="300px" width="300px">
          </div>
<div class="squad">
    <h2>SQUAD</h2>
    <ul>
        <li id="Cap">Lionel Messi</li>
        <li>Luis Suarez</li>
        <li id="GK">Ter Stegen</li>
        <li>Gerard Pique</li>
        <li>Clement Lenglet</li>
        <li>Jordi Alba</li>
        <li>Nelson Semedo</li>
        <li>Frenkie De Jong</li>
        <li>Antoine Greizmann</li>
        <li>Sergio Busquets</li>
        <li>Ivan Rakitic</li>
    </ul>
</div>
<button type="button" class="btn btn-light"><a href="{% url 'bday:birthday' %}"">Back</a></button>
      </body>
  </html>  

lecture3/hi/templates/hello/sq.html
{% extends "tasks/index.html"%}
{% load static %}
{% block body %}
<title>Square</title>

<body>
   <h1 style="color:blue;">The square of the number {{num}} is : {{res}}</h1>
   
</body>
{% endblock %}

lecture3/tasks/templates/tasks/index.html
<!DOCTYPE html>
<head>
    <title>Letters</title>
</head>
<body>
    <ul>{% for let in letters %}
    <li>{{let}}</li>
    {% endfor %}
    </ul>
    {% block body %}
    {% endblock %}
    <form action="{% url 'greek' %}" method="POST">
        {% csrf_token %}
        {{form}}
        <button type="submit">Sub</button>
    </form>
    <a href="{% url 'club' %}">FCB</a>
    </body>